import type { Challenge } from '@/types';

export const challenges: Challenge[] = [
  {
    day: 1,
    title: 'Observe Without Judging',
    description: 'Notice what bothers you today without trying to fix it. Just watch.',
    reflectionPrompt: 'What did you notice about yourself when you stopped trying to fix things?',
  },
  {
    day: 2,
    title: 'Delay Reactions',
    description: 'Pause before replying, reacting, or overexplaining. Breathe first.',
    reflectionPrompt: 'How did it feel to pause? What did you observe in that space of silence?',
  },
  {
    day: 3,
    title: 'Digital Detox Hour',
    description: 'One hour with no phone, no scrolling, no checking. Just exist.',
    reflectionPrompt: 'What thoughts arrived when you stepped away from the screen?',
  },
  {
    day: 4,
    title: 'Breathe First',
    description: 'Take three deep breaths before every conversation today. Every single one.',
    reflectionPrompt: 'How did a conscious breath change the quality of your interactions?',
  },
  {
    day: 5,
    title: 'Name Your Feelings',
    description: 'Write down three emotions you felt today without judgment or explanation.',
    reflectionPrompt: 'What pattern did you notice in the feelings you identified today?',
  },
  {
    day: 6,
    title: 'Say No Once',
    description: "Decline one thing that doesn't align with your peace today. No guilt.",
    reflectionPrompt: 'How did it feel to say no? What did you protect by doing so?',
  },
  {
    day: 7,
    title: 'Phone-Free Morning',
    description: 'Keep your phone away for the first 30 minutes after waking. Start gently.',
    reflectionPrompt: 'What did you experience in the quiet of your phone-free morning?',
  },
  {
    day: 8,
    title: 'Sit With Discomfort',
    description: "Let one uncomfortable feeling exist without trying to fix or escape it.",
    reflectionPrompt: 'What surprised you about sitting with discomfort instead of escaping?',
  },
  {
    day: 9,
    title: 'Body Check-In',
    description: "Pause three times today and notice where you're holding tension in your body.",
    reflectionPrompt: 'Where does your body hold stress? What does it need from you?',
  },
  {
    day: 10,
    title: 'Speak Less, Listen More',
    description: 'In every conversation today, let others finish before you respond.',
    reflectionPrompt: 'What did you hear more clearly when you truly listened today?',
  },
  {
    day: 11,
    title: 'Let Go of One Thing',
    description: "Choose one worry you've been carrying. Consciously release it today.",
    reflectionPrompt: 'What does it feel like to consciously release something you cannot control?',
  },
  {
    day: 12,
    title: 'Gratitude Without Reason',
    description: "Write three things you're grateful for. No explanations needed.",
    reflectionPrompt: 'What do these three things reveal about what matters most to you?',
  },
  {
    day: 13,
    title: 'Unfollow One Thing',
    description: 'Remove one source of comparison or noise from your life today.',
    reflectionPrompt: 'What shifted in your mental space after removing that source of noise?',
  },
  {
    day: 14,
    title: 'Move Gently',
    description: 'Ten minutes of gentle movement — stretch, walk slowly, or dance alone.',
    reflectionPrompt: 'How did your body feel after gentle movement? What changed inside you?',
  },
  {
    day: 15,
    title: 'Write It Out',
    description: 'Fill one page with whatever is on your mind. No editing, no judgment.',
    reflectionPrompt: 'What emerged when you wrote without editing or filtering yourself?',
  },
  {
    day: 16,
    title: 'Rest Without Guilt',
    description: "Take a nap, sit quietly, or simply be still for 20 minutes. It's allowed.",
    reflectionPrompt: 'What resistance did you feel when you tried to rest without guilt?',
  },
  {
    day: 17,
    title: 'Protect Your Energy',
    description: 'Identify one person or situation draining you. Create gentle distance.',
    reflectionPrompt: 'What did you learn about your own energy by creating that distance?',
  },
  {
    day: 18,
    title: 'Affirmation Practice',
    description: 'Choose one affirmation and say it out loud five times. Mean every word.',
    reflectionPrompt: 'What did you notice about how the affirmation felt as you said it?',
  },
  {
    day: 19,
    title: 'Celebrate Small Wins',
    description: 'List three things you did well this week, however small they seem.',
    reflectionPrompt: 'What does celebrating yourself feel like? What made it hard or easy?',
  },
  {
    day: 20,
    title: 'Create Without Purpose',
    description: 'Draw, hum, cook, write — make something with no goal and no audience.',
    reflectionPrompt: 'What did it feel like to create without needing a result or an audience?',
  },
  {
    day: 21,
    title: 'Return to Yourself',
    description: "Spend today doing only what feels good to your soul. You've earned it.",
    reflectionPrompt: 'What does returning to yourself mean to you? What did you rediscover?',
  },
];
